

export default {
  LOAD: {
    EMPLOYEE: {
      SUCCESS: 'LOAD_EMPLOYEE_SUCCESS',
    },
    EMPLOYEES: {
      SUCCESS: 'LOAD_EMPLOYEES_SUCCESS',
    },
    DEPARTMENT: {
      SUCCESS: 'LOAD_DEPARTMENT_SUCCESS'
    },
    DEPARTMENTS: {
      SUCCESS: 'LOAD_DEPARTMENTS_SUCCESS',
      EMPTIES: {
        SUCCESS: 'LOAD_DEPARTMENTS_EMPTIES_SUCCESS'
      }
    },
    PROFILE: {
      SUCCESS: 'LOAD_PROFILE_SUCCESS'
    },
  },
  UPDATE: {
    EMPLOYEE:{
      SUCCESS: 'UPDATE_EMPLOYEE_SUCCESS'
    },
    DEPARTMENT:{
      SUCCESS: 'UPDATE_DEPARTMENT_SUCCESS'
    },
    PROFILE: {
      SUCCESS: 'LOAD_PROFILE_SUCCESS',
    },

  },
  CREATE: {
    EMPLOYEE:{
      SUCCESS: 'CREATE_EMPLOYEE_SUCCESS'
    },
    DEPARTMENT:{
      SUCCESS: 'CREATE_DEPARTMENT_SUCCESS'
    },
    PROFILE: {
      SUCCESS: 'CREATE_PROFILE_SUCCESS',
      FAILED: 'FAILED_PROFILE_SUCCESS'
    },
  },
  DELETE: {
    EMPLOYEE:{
      SUCCESS: 'DELETE_EMPLOYEE_SUCCESS'
    },
    DEPARTMENT:{
      SUCCESS: 'DELETE_DEPARTMENT_SUCCESS'
    }
  },
  LOGIN: {
    SUCCESS: 'LOGIN_SUCCESS'
  },
  LOGOFF: {
    SUCCESS: 'LOGOFF_SUCCESS'
  }
};